export enum JuzStatus {
  AVAILABLE = 'AVAILABLE',
  RESERVED = 'RESERVED'
}

export enum ReadingStatus {
  NOT_STARTED = 'NOT_STARTED',
  READING = 'READING',
  COMPLETED = 'COMPLETED'
}

export enum KhatmaStatus {
  OPEN = 'OPEN',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export interface Juz {
  id: number;
  label: string;
  status: JuzStatus;
  readingStatus: ReadingStatus;
  reservedBy?: string;
  reservedById?: string;
  reservedAt?: string;
}

export enum KhatmaVisibility {
  PUBLIC = 'PUBLIC',
  PRIVATE = 'PRIVATE'
}

export interface Khatma {
  id: string;
  title: string;
  startDate: string;
  endDate: string;
  status: KhatmaStatus;
  visibility: KhatmaVisibility;
  parts: Juz[];
  createdBy: string;
  adminComment?: string;
  completionDua?: string; // Generated by AI
}

export interface User {
  name: string;
  isAdmin: boolean;
}